@Crypto.Api_HostAddress = http://localhost:5010

POST {{Crypto.Api_HostAddress}}/Crypto/
Accept: application/json
Content-Type: application/json

{
    "code": "EUR", 
    "askedCodes": ["ETH", "LTC", "XRP"] 
}

